server:
  port: 8086
  
spring:
  application:
    name: eshop-product-service
  datasource:
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    url: jdbc:mysql://118.190.71.215:3308/eshop
  rabbitmq:
    host: 118.190.71.215
    port: 15672  
    username: guest  
    password: guest
   
   
   
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8080/eureka
    
    

    
 
  