server:
  port: 8082
spring:
  application:
    name: eureka-client
    
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8080/eureka
    fetch-registry: false
    
    
    
 
  