server:
  port: 8082
spring:
  application:
    name: eureka-client
    
eureka:

  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8081/eureka
    
    

    
 
  