server:
  port: 8081
spring:
  application:
    name: eureka-client
    
eureka:

  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8080/eureka
    
    

    
 
  