server:
  port: 8088
  
spring:
  application:
    name: eshop-inventory-service
  datasource:
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    url: jdbc:mysql://118.190.71.215:3308/eshop
    
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8080/eureka
    
    

    
 
  