server:
  port: 8085
  
spring:
  application:
    name: user-service
  datasource:
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    url: jdbc:mysql://localhost:3306/eshop
    
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8080/eureka
    
    

    
 
  