server:
  port: 8080
spring:
  application:
    name: eureka-server
    
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
    fetch-registry: false
    
    
    
 
  