server:
  port: 8081
spring:
  application:
    name: eshop-server
    
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
    fetch-registry: false
    
    
    
 
  